package router

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// DefaultConfigPath is where init writes models.yaml.
func DefaultConfigPath() string {
	if home, err := os.UserHomeDir(); err == nil {
		return filepath.Join(home, ".config", "promptrouter", "models.yaml")
	}
	return "models.yaml"
}

// Plan is the user's answers from the wizard, turned into a config file.
type Plan struct {
	JudgeModel  string
	LocalModel  string // ollama model for the EASY tier and local fallback
	CloudEngine string // "hermes", "openrouter", or "" for none
	CloudHard   string // cloud model for HARD
	CloudExpert string // cloud model for EXPERT
	OllamaURL   string
	LogFile     string

	// Score mode (optional). When Levels is non-empty, Render writes a
	// score-based config instead of the categorical EASY/HARD/EXPERT tiers.
	Levels []LevelSpec
}

// LevelSpec is one user-defined band for a score-mode plan: a name, the score
// at which it starts, and the ordered engine chain it routes to.
type LevelSpec struct {
	Name     string
	MinScore int
	Chain    []Engine
}

// RenderScore writes a score-mode models.yaml from the plan's levels.
func (p Plan) RenderScore() string {
	var b strings.Builder
	b.WriteString("# promptrouter config. Generated by `route init`, safe to edit.\n")
	b.WriteString("# The judge scores each task 0-100; the highest level whose\n")
	b.WriteString("# min_score the task clears wins, then its chain runs top to bottom.\n\n")

	b.WriteString("judge:\n")
	b.WriteString("  model: " + p.JudgeModel + "\n")
	b.WriteString("  mode: score\n\n")

	b.WriteString("levels:\n")
	for _, l := range p.Levels {
		b.WriteString("  - name: " + l.Name + "\n")
		fmt.Fprintf(&b, "    min_score: %d\n", l.MinScore)
		b.WriteString("    chain:\n")
		for _, e := range l.Chain {
			b.WriteString("      - engine: " + e.Kind + "\n        model: " + e.Model + "\n")
		}
	}
	b.WriteString("\n")

	b.WriteString("defaults:\n")
	b.WriteString("  ollama_url: \"" + p.OllamaURL + "\"\n")
	b.WriteString("  max_retries: 1\n")
	b.WriteString("  retry_backoff: 0.5\n")
	if p.LogFile != "" {
		b.WriteString("  log_file: \"" + p.LogFile + "\"\n")
	} else {
		b.WriteString("  log_file: \"\"\n")
	}
	return b.String()
}

// Render turns a Plan into models.yaml text. Written by hand (not yaml.Marshal)
// so the file keeps comments and a stable, readable shape.
func (p Plan) Render() string {
	if len(p.Levels) > 0 {
		return p.RenderScore()
	}
	var b strings.Builder
	b.WriteString("# promptrouter config. Generated by `route init`, safe to edit.\n")
	b.WriteString("# A task is judged into a tier, then routed down that tier's chain.\n\n")

	b.WriteString("judge:\n")
	b.WriteString("  model: " + p.JudgeModel + "\n\n")

	b.WriteString("tiers:\n")

	// EASY: always local.
	b.WriteString("  EASY:\n    chain:\n")
	b.WriteString("      - engine: ollama\n        model: " + p.LocalModel + "\n\n")

	// HARD: cloud first (if chosen), local fallback.
	b.WriteString("  HARD:\n    chain:\n")
	if p.CloudEngine != "" && p.CloudHard != "" {
		b.WriteString("      - engine: " + p.CloudEngine + "\n        model: " + p.CloudHard + "\n")
	}
	b.WriteString("      - engine: ollama\n        model: " + p.LocalModel + "\n\n")

	// EXPERT: cloud first (if chosen), local fallback.
	b.WriteString("  EXPERT:\n    chain:\n")
	if p.CloudEngine != "" && p.CloudExpert != "" {
		b.WriteString("      - engine: " + p.CloudEngine + "\n        model: " + p.CloudExpert + "\n")
	}
	b.WriteString("      - engine: ollama\n        model: " + p.LocalModel + "\n\n")

	b.WriteString("defaults:\n")
	b.WriteString("  fallback_tier: HARD\n")
	b.WriteString("  ollama_url: \"" + p.OllamaURL + "\"\n")
	b.WriteString("  max_retries: 1\n")
	b.WriteString("  retry_backoff: 0.5\n")
	if p.LogFile != "" {
		b.WriteString("  log_file: \"" + p.LogFile + "\"\n")
	} else {
		b.WriteString("  log_file: \"\"\n")
	}
	return b.String()
}

// Save writes the rendered config to path, creating parent dirs.
func (p Plan) Save(path string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(p.Render()), 0o644)
}

// Validate checks that the rendered plan parses and passes config validation,
// so init never writes a file that route cannot load.
func (p Plan) Validate() error {
	var c Config
	if err := parseInto(p.Render(), &c); err != nil {
		return err
	}
	if err := c.validate(); err != nil {
		return err
	}
	return nil
}

func parseInto(text string, c *Config) error {
	tmp, err := os.CreateTemp("", "promptrouter-*.yaml")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.WriteString(text); err != nil {
		return err
	}
	tmp.Close()
	loaded, err := Load(tmp.Name())
	if err != nil {
		return fmt.Errorf("generated config is invalid: %w", err)
	}
	*c = *loaded
	return nil
}
